spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker    username: ftadm    password: nithish651    driver-class-name: org.postgresql.Driver  jpa:    database-platform: org.hibernate.dialect.PostgreSQLDialect